Feature: demoblaze signup script

  Background:
    * url 'https://api.demoblaze.com'

  Scenario: signup with a non autogenerated user
    * def user =
      """
      {
        "username": "karate111",
        "password": "a2FyYXR1MTIz"
      }
      """

    Given path 'signup'
    And request user
    When method post
    Then status 200